title: OpusTheRobot
name: Liam Arbuckle
email: opus@allianceofdroids.org.au
description: Games Developer

baseurl: "/blog"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/photo-1510519138101-570d1dca3d66.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/run-debug-vs-code.png

project_one: "Stellarios"
project_one_description: Stellarios is a suite of games that ACORD has created as well as applications to control our robots. Available to all ACORD members.
project_one_url: https://gitlab.com/acord-robotics/robodev/stellarios
project_one_icon: gitlab

project_two: ACORD Robotics
project_two_description: ACORD is an Australian Robotics company that I founded with my cousin, Nicholas. We create stunning robots for uses in all fields, including geology, aeronautics, and mental health. We also create great quality games, for example Star Sailors & Pythons of Mars.
project_two_url: http://allianceofdroids.org.au
project_button: Portal
project_two_icon: photo_camera

project_three: Life Size R2-D2 Replica
project_three_description: I'm building a life-size R2-D2. Thanks to the [R2-D2 Builders Club](http://astromech.net), the blueprints (CS:R) are movie-accurate. This R2 unit will be controlled via an Android/iOS app called R2-Touch by [Curious Marc](http://curiousmarc.com). I've built other droids before, including a steampunk-themed R2 (Sp-D2), however this is the first one that I've built that will have electronics.
project_three_url: http://gitlab.com/acord-robotics/robodev/lifesizer2/
project_three_icon: photo_camera

project_four: Mushlantis - A Minecraft World
project_four_description: Mushlantis is a world in Minecraft that I've been playing for three years. I post videos on Mushlantis once a week and am currently working on building a village in a Mushroom Biome.
project_three_url: http://gitlab.com/irisdroidology/minecraft-mushlantos
project_four_icon: photo_camera

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: android
  - name: apple
  - name: atom
  - name: bitbucket
  - name: c
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: firefox
  - name: git
  - name: gitlab
  - name: html5
  - name: javascript
  - name: linux
  - name: php
  - name: python
  - name: slack
  - name: visualstudio

icon_size: 40 # font-size of icons in px
colored:  # Leave blank for black and white icons and colored for coloured icons

project_button: Github

github: https://github.com/IrisDroidology
medium: https://medium.com/@limodroid

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://irisdroidology.github.io/opus #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
remote_theme: jameshamann/jekyll-material-theme 
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  
collections:
  - medium_posts
