---
title: OpusTheRobot
timezone: Australia/Perth
collections:
  external_feed:
    title: External Feed
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Liam Arbuckle
email: opus@allianceofdroids.org.au
description: Games Developer
baseurl: 
url: http://irisdroidology.github.io/opus
display_footer: inital
parallax_image_one: assets/images/photo-1510519138101-570d1dca3d66.jpg
parallax_image_two: assets/images/run-debug-vs-code.png
project_one: Stellarios
project_one_description: Stellarios is a suite of games that ACORD has created as
  well as applications to control our robots. Available to all ACORD members.
project_one_url: https://gitlab.com/acord-robotics/robodev/stellarios
project_one_icon: gitlab
project_two: ACORD Robotics
project_two_description: ACORD is an Australian Robotics company that I founded with
  my cousin, Nicholas. We create stunning robots for uses in all fields, including
  geology, aeronautics, and mental health. We also create great quality games, for
  example Star Sailors & Pythons of Mars.
project_two_url: http://allianceofdroids.org.au
project_button: Github
project_two_icon: photo_camera
project_three: Life Size R2-D2 Replica
project_three_description: I'm building a life-size R2-D2. Thanks to the R2-D2 Builders
  Club - http://astromech.net, the blueprints (CS:R) are movie-accurate. This R2 unit
  will be controlled via an Android/iOS app called R2-Touch by Curious Marc - http://curiousmarc.com.
  I've built other droids before, including a steampunk-themed R2 (Sp-D2), however
  this is the first one that I've built that will have electronics.
project_three_url: http://gitlab.com/acord-robotics/robodev/lifesizer2/
project_three_icon: photo_camera
project_four: Mushlantis - A Minecraft World
project_four_description: Mushlantis is a world in Minecraft that I've been playing
  for three years. I post videos on Mushlantis once a week and am currently working
  on building a village in a Mushroom Biome.
project_four_url: http://gitlab.com/irisdroidology/minecraft-mushlantos
project_four_icon: photo_camera
project_five: My Computer
project_five_description: My Gaming/Code PC has 16gb RAM, an Nvidea 1070ti, Intel
  i5, and a 27 inch AOC monitor. I create my youtube videos and my code projects on
  it.
project_five_url: http://acord.tech/my-pc
project_six: My Writing
project_six_description: I've always loved writing. Here's a link to all my writing
project_six_url: http://acord.tech/limo-s-writing
project_six_icon: photo_camera
portfolio_heading: Code Portfolio
portfolio_type: cards
syntax_highlighting: true
skills:
- name: android
- name: apple
- name: atom
- name: bitbucket
- name: c
- name: cplusplus
- name: csharp
- name: css3
- name: firefox
- name: git
- name: github
- name: gitlab
- name: html5
- name: javascript
- name: linux
- name: photoshop
- name: php
- name: python
- name: slack
- name: visualstudio
icon_size: 35
colored: colored
github: https://github.com/IrisDroidology
medium: https://medium.com/@limodroid
tag_manager_id: 
google_analytics_tracking_id: 
cookies_banner: none
cookie_accept_message: Thanks!
markdown: kramdown
remote_theme: jameshamann/jekyll-material-theme
permalink: pretty
plugins:
- jekyll-feed
- jekyll-assets
- jekyll-minifier

collections:
  - medium_posts
